# Generated by Django 2.2.3 on 2019-07-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('gauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessId',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_id', models.CharField(max_length=80)),
            ],
        ),
    ]
