# Generated by Django 2.2.3 on 2019-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0002_sessid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessid',
            name='session',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='sessid',
            name='email_id',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
