# Generated by Django 2.2.3 on 2019-07-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0003_auto_20190705_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessid',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='sessid',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
