# Generated by Django 2.2.3 on 2019-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0004_auto_20190705_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessid',
            name='access_code',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
