# Generated by Django 2.2.3 on 2019-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0006_remove_sessid_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessid',
            name='access_code',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
