# Generated by Django 2.2.3 on 2019-07-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0008_sessid_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessid',
            name='credential',
        ),
    ]
