# Generated by Django 2.2.3 on 2019-07-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0009_remove_sessid_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessid',
            name='http',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
