# Generated by Django 2.2.3 on 2019-07-05 19:54

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('gauth', '0010_sessid_http'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessid',
            name='http',
        ),
        migrations.AddField(
            model_name='sessid',
            name='credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
