# Generated by Django 2.2.3 on 2019-07-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=80, null=True)),
                ('widgets', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
