# Generated by Django 2.2.3 on 2019-07-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wids',
            name='remarks',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
